name: Auto Update M3U Playlist
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Fetch and Update
        run: |
          python - <<EOF
          import requests
          from bs4 import BeautifulSoup
          url = "https://halu.serv00.net/poli.php"
          try:
              res = requests.get(url, timeout=30)
              res.encoding = 'utf-8'
              soup = BeautifulSoup(res.text, 'html.parser')
              channels = []
              for a in soup.find_all('a', href=True):
                  if '.m3u8' in a['href']:
                      name = a.get_text(strip=True) or "Unknown"
                      raw_link = a['href']
                      link = raw_link[:57] + 'n' + raw_link[58:] if len(raw_link) >= 58 else raw_link
                      img_tag = a.find_previous('img') or a.find('img')
                      img = img_tag['src'] if img_tag else ""
                      channels.append(f'#EXTINF:-1 tvg-logo="{img}",{name}\n{link}')
              if channels:
                  with open("wwch2025.m3u", "w", encoding="utf-8") as f:
                      f.write("#EXTM3U\n" + "\n".join(channels))
          except Exception as e: print(e)
          EOF

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wwch2025.m3u
          git commit -m "Auto Update" || exit 0
          git push
